sudo: required

services:
  - docker


install: docker build -t johnrellis/johnrellis-users-api:$TRAVIS_BUILD_NUMBER .

before_script: docker run johnrellis/johnrellis-users-api:$TRAVIS_BUILD_NUMBER npm run lint

script: 
  - docker run johnrellis/johnrellis-users-api:$TRAVIS_BUILD_NUMBER npm test
  - docker-compose -f docker-compose.yml up -d
  - sleep 10
  - docker exec -it api npm run integration
  - docker-compose -f docker-compose.yml down
  - sleep 10

deploy:
  provider: script
  script: bash docker_push.bash
