version: "2"
services:
  api:
    image: "johnrellis/johnrellis-users-api:$TRAVIS_BUILD_NUMBER"
    container_name: api
    restart: always
    build: .
    ports:
      - "3000:3000"
    command: node app.js
    links:
      - mongo
    environment:
        - MONGODB_HOST=mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"