# johnrellis-users-api
:toc:

image:https://travis-ci.org/johnrellis/johnrellis-users-api.svg?branch=master["Build Status", link="https://travis-ci.org/johnrellis/johnrellis-users-api"]

An API for performing CRUDL on users

## Stack

* API - Node.js
* Persistence - Mongodb

## Environment

Required Environment Variables

* MONGODB_HOST e.g. `export MONGODB_HOST=localhost`

## Code Quality and Testing

### Linting

This repo is linted via eslint, all configuration is located in `.eslintrc.js`.  Linting is run as a pre-commit hook via the `pre-commit` npm module and via the npm command 

`npm run lint`

### Unit Testing

Unit tests are run via the npm command

`npm test`


Code coverage is provided by `istanbul` via the `nyc` npm module.  The unit tests do not utilise mongodb.  Mocking of required dependencies is done via `mockery` with `sinon` utilised to create stubs and spies.

### Integration testing

Integration tests are run via the npm command

`npm run integration`

A connection to mongodb is required and the `MONGODB_HOST` environment variables may be set. Integration tests require the node application to be running in a separate process via

`node app.js`

The supplied 'docker-compose.yml' can also be used to start the application with a mongodb instance.  Integration tests can then be run against this instance if required.

`docker-compose -f docker-compose.yml up -d`
`docker exec -it api npm run integration`

## Build

Built using travis

image:https://travis-ci.org/johnrellis/johnrellis-users-api.svg?branch=master["Build Status", link="https://travis-ci.org/johnrellis/johnrellis-users-api"]


The travis build 'script' contains a number of steps that can be summarised as

* lint
* unit test
* integration test
* deploy

## Deployment 

Deployed to https://hub.docker.com/r/johnrellis/johnrellis-users-api and tagged with `TRAVIS_BUILD_NUMBER`

## Run

`docker run -p 3000:3000 johnrellis/users-api:1 node app.js` where '1' is the `TRAVIS_BUILD_NUMBER`

Note that this requires a mongo db instance to be running on a host declared as `MONGODB_HOST` in the environment

Alternatively, `docker-compose.yml` may be altered to target a specific tag and application can be run with

`docker-compose -f docker-compose.yml up -d`

Once running, the API will be available on `http://localhost:3000/api/v1/users`

## TODO 

This repo is essentially a demonstration and the following real world scenarios have not yet been implemented

* Authentication and Authorisation on an API level
* Mongodb Authentication - currently uses default port without password protection supported
