# johnrellis-users-api
:toc:

image:https://travis-ci.org/johnrellis/johnrellis-users-api.svg?branch=master["Build Status", link="https://travis-ci.org/johnrellis/johnrellis-users-api"]

An API for performing CRUDL on users

## Running and testing with docker-compose

To run the application, simply use docker-compose

`docker-compose -f docker-compose.yml up -d`

This will create 2 services, api and mongo.

To verify that the api is running, run 

`curl http://localhost:3000`

A response with a 200 HTTP code will respond with the message "I am alive".

Unit and integration tests can be run with the following commands respectively :

* `docker exec -it api npm run test`
* `docker exec -it api npm run integration`

## A quick intro to the API

The following actions are currently supported:

* CREATE - POST /api/v1/users with a json body
* READ - GET /api/v1/users/:id 
* UPDATE- PUT /api/v1/users/:id with a json body, if `id` does not exist, a new user will be created
* DELETE - DELETE /api/v1/users/:id 
* LIST - GET /api/v1/users
** user property names can be used to filter e.g. `?email=john@home.com`.  Full match is currently required, less than or greater than queries are not yet supported.  Pagination is supported via `limit`, `offset` `sort` e.g. `?limit=10&offset=10&sort=-email` to sort descending or `?limit=10&offset=10&sort=email` for ascending.  Pagination is managed by the `paginationAndSort.js` middleware.


## Stack

* API - Node.js - engine configured to greater or equal to v8.11.1
* Persistence - Mongodb - tested against version 3.6 - the integration tests will continue to test against the latest version until an incompatibility fails the build.  Mongoose is used as an ORM.

## Running without docker-cpmpose

If running without the docker-compose.yml, the following environment variable are required:

* MONGODB_HOST e.g. `export MONGODB_HOST=localhost`

With a mongodb instance running on on the MONGODB_HOST with the default port exposed, the app can then be started with `node app.js`.  Currently, authentication or custom mongodb ports are not implemented

## Code Quality and Testing

### Linting

This repo is linted via eslint, all configuration is located in `.eslintrc.js`.  Linting is run as a pre-commit hook via the `pre-commit` npm module and via the npm command 

`npm run lint`

### Unit Testing

Unit tests are run via the npm command

`npm test`

The `mockery` npm module is used in conjunction with `sinon` and number of `sinon` variations to enable mocking in the unit tests.

### Code coverage

Code coverage is provided by `istanbul` via the `nyc` npm module during the unit test phase.

### Integration testing

Integration tests are run via the npm command

`npm run integration`

A connection to mongodb is required and the `MONGODB_HOST` environment variables may be set. Integration tests require the node application to be running in a separate process via

`node app.js`

The supplied 'docker-compose.yml' can also be used to start the application with a mongodb instance. See the "Running and testing with docker-compose" section above.

## Build

Built using travis

image:https://travis-ci.org/johnrellis/johnrellis-users-api.svg?branch=master["Build Status", link="https://travis-ci.org/johnrellis/johnrellis-users-api"]


The travis build 'script' contains a number of steps that can be summarised as

* lint
* unit test
* integration test
* deploy

## Deployment 

Deployed to https://hub.docker.com/r/johnrellis/johnrellis-users-api and tagged with `TRAVIS_BUILD_NUMBER`


## TODO 

This repo is essentially a demonstration and the following real world scenarios have not yet been implemented

* Authentication and Authorisation on an API level, the `passport` npm module might be a good place to start for Authentication
* Mongodb Authentication - currently uses default port without password protection, this is not an ideal scenario for production, all mongodb connections should be secured
* Validation of input into the API to ensure the input makes sense, the `jsonschema` npm module is a viable option
* Remove as many instanbul ignores as possible, currently there are a small number, such as in app.js but this needs to be evaluated for it's value to the quality of the deployment if the integration tests can cover any of these scenarios
* API documentation required, Swagger is a viable option
* Add more properties to the User model to mimic a real world user based API
* Enable `less than`, `greater than`, `like` queries in the filtering of the list endpoint
